-- CREATE TABLE QUERY
CREATE TABLE REGIONS
(
    REGION_ID INT PRIMARY KEY,
    REGION_NAME VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE COUNTRIES
(
    COUNTRY_ID CHAR(2) PRIMARY KEY,
    COUNTRY_NAME VARCHAR2(50) NOT NULL UNIQUE,
    REGION_ID INT NOT NULL,
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(REGION_ID) ON DELETE CASCADE
);

CREATE TABLE LOCATIONS
(
    LOCATION_ID INT PRIMARY KEY,
    STREET_ADDRESS VARCHAR2(100),
    POSTAL_CODE VARCHAR2(20),
    CITY VARCHAR2(50) NOT NULL,
    STATE_PROVINCE VARCHAR2(50),
    COUNTRY_ID CHAR(2) NOT NULL,
    FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID) ON DELETE CASCADE
);

CREATE TABLE DEPARTMENTS
(
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(50) NOT NULL UNIQUE,
    MANAGER_ID INT,
    LOCATION_ID INT,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID) ON DELETE CASCADE
);

CREATE TABLE JOBS
(
    JOB_ID VARCHAR(10) PRIMARY KEY,
    JOB_TITLE VARCHAR2(50) NOT NULL UNIQUE,
    MIN_SALARY DECIMAL(10, 2),
    MAX_SALARY DECIMAL(10, 2)
);

CREATE TABLE EMPLOYEES
(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL UNIQUE,
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE NOT NULL,
    JOB_ID VARCHAR(10) NOT NULL,
    SALARY DECIMAL(10, 2) CHECK (SALARY > 0),
    COMMISSION_PCT DECIMAL(3, 2),
    MANAGER_ID INT,
    DEPARTMENT_ID INT,
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE SET NULL
);

CREATE TABLE JOB_HISTORY
(
    EMPLOYEE_ID INT,
    START_DATE DATE,
    END_DATE DATE,
    JOB_ID VARCHAR(10),
    DEPARTMENT_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID) ON DELETE CASCADE,
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID) ON DELETE CASCADE,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID) ON DELETE CASCADE,
    PRIMARY KEY (EMPLOYEE_ID, START_DATE)
);




